# Generated by Django 4.2.1 on 2023-07-22 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='todo_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='todo_level',
            field=models.IntegerField(choices=[(0, 'Not Provided'), (1, 'Low'), (2, 'Medium'), (3, 'Urgent'), (4, 'Now')], default=0),
        ),
    ]
